server:
  port: 8080
spring:
  application:
    name: back
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
  batch:
    job:
      enabled: false
logging:
  level:
    com.back: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
custom:
  system:
    apiKey: ${SYSTEM_API_KEY}
  services:
    member-url: http://localhost:8080
  global:
    internalBackUrl: http://localhost:${server.port:8080}
    holdingMemberId: 2
  jwt:
    secretKey: ${JWT_SECRET_KEY}
  accessToken:
    expirationSeconds: ${ACCESS_TOKEN_EXPIRATION_SECONDS}
  payout:
    readyWaitingDays: 14
  member:
    password:
      changeDays: 90
  market:
    toss:
      payments:
        secretKey: ${TOSS_PAYMENTS_SECRET_KEY:}
    product:
      payoutRate: 90